import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        // paddingVertical: 20,
        // backgroundColor: 'rgba(255, 255, 255, 0)',
        width: '100%',
    },
    container: {
        flex: 1,
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        padding: '5%',
    },
    gradientContainer: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    registerCard: {
        width: '90%',
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        borderRadius: 36,
        padding: 35,
        paddingTop: 0,
        // overflow: 'hidden',
    },
    registerTitle: {
        fontSize: 30,
        fontWeight: '600',
        textAlign: 'center',
        marginVertical: 10,
    },
    label: {
        marginTop: 10,
        marginBottom: 4,
        fontSize: 14,
        color: '#000',
    },
    input: {
        // borderWidth: 1,
        // borderColor: '#ddd',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 14,
        fontSize: 12,
        backgroundColor: '#fff',
    },
    passwordRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    forgot: {
        color: '#666',
        fontSize: 12,
    },
    centeredViewCaptcha: {
        display: 'flex',
        alignItems: 'center',
    },
    captcha: {
        marginVertical: 15,
        borderRadius: 8,
        padding: 12,
        backgroundColor: '#f0f0f0',
        alignItems: 'center',
        width: '70%',
    },
    createAccBtn: {
        backgroundColor: '#284aa5',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 35,
    },
    createAccText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    orText: {
        textAlign: 'center',
        textAlignVertical: 'center',
        marginVertical: 10,
        color: '#888',
        backgroundColor: '#fff',
        padding: 5,
        height: 30,
        width: 30,
        borderRadius: 15,
    },
    signInBtn: {
        backgroundColor: '#fff',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
    },
    signInText: {
        color: '#666',
        fontWeight: '500',
    },
    lineBesideOr: {
        backgroundColor: '#eee',
        width: 110,
        height: 2,
    },
});
