import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        // paddingVertical: 20,
        // backgroundColor: 'rgba(255, 255, 255, 0)',
        width: '100%',
    },
    container: {
        flex: 1,
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    gradientContainer: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginCard: {
        width: '90%',
        backgroundColor: 'rgba(30, 30, 30, 0.7)',
        borderRadius: 36,
        padding: 40,
        paddingTop: 0,
    },
    loginTitle: {
        fontSize: 30,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 10,
        color: '#fff',
    },
    label: {
        marginTop: 10,
        marginBottom: 4,
        fontSize: 14,
        color: '#ddd',
    },
    input: {
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        backgroundColor: '#444',
        color: '#fff',
        maxHeight: 45,
        // height: 30,
    },
    passwordRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    forgot: {
        color: '#aaa',
        fontSize: 12,
    },
    centeredViewCaptcha: {
        display: 'flex',
        alignItems: 'center',
    },
    captcha: {
        marginVertical: 15,
        borderRadius: 8,
        padding: 12,
        backgroundColor: '#444',
        alignItems: 'center',
        width: '70%',
    },
    signInBtn: {
        backgroundColor: '#284aa5',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 5,
    },
    signInText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    orText: {
        textAlign: 'center',
        textAlignVertical: 'center',
        marginVertical: 10,
        color: '#aaa',
        backgroundColor: '#333',
        padding: 5,
        height: 30,
        width: 30,
        borderRadius: 15,
    },
    registerBtn: {
        backgroundColor: '#333',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
    },
    registerText: {
        color: '#ccc',
        fontWeight: '500',
    },
    lineBesideOr: {
        backgroundColor: '#444',
        width: '35%',
        height: 2,
    },
});
